# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: terminal 1
    before: echo 'before'
    init: |
          echo 'init script' # runs during prebuild
          'pip install -r requirements.txt'

    command: |
            python work1.py
             echo 'ssss'

  - name: terminal 2
    before: echo 'beforelllll'
    init: |
          echo 'kkkkkllll'

    command: |
             echo 'kkkkk'
             pip list

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
